// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwsxmaaccujjxvuelvlc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3c3htYWFjY3Vqanh2dWVsdmxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1NjM0NjUsImV4cCI6MjA2NjEzOTQ2NX0.owD_2ljnqYvss4O-u8A_acY6orE_VKGukgohgdzzy6s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);